#!/usr/bin/env bash

#A  bash script that gives information about the school file 
#   Check if file is a regular file or not
#   Checks if a file exists or not
#   Checks if file is empty or not

filename="school"

if [ -f "$filename" ]; then
	echo "school file exists"
	echo "school is a regular file"
else
	echo "school file does not exist" 
fi

if [ -s "$filename" ]; then
	echo "schoool file is not empty"
else
	echo "school file is empty"

fi
